### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by annatmmm** [tvaidyan/time-entry-system-angular-ui#1]
Hi there! 
I would love to test out the project features but since there is no sign-up option for a new user account, and I can't seem to find a demo user login ID, I have not been able to access the system. I was wondering if there is any way I can access the system. Thank you!

**Comment by tvaidyan** [comment]
Hello!  This project is just the frontend portion.  You can find a backend written in C#/ASP.NET Core on my account, as well, here: https://github.com/tvaidyan/time-entry-system-api  This backend uses EntityFramework and seeds the database with a test user upon initialization.  Checkout the https://github.com/tvaidyan/time-entry-system-api/blob/master/TimeEntryApi.Infrastructure/Data/TimeEntryDbContext.cs file.

Having said all this, this is by no means an active project... this was more or less me trying out a few things a few years back and just dumping the source code here.  Please feel free do with it, as you wish.
